# Get the list of doctors
GET http://localhost:3000/doctors HTTP/1.1


###

# GET the list of doctors with the id 

GET http://localhost:3000/doctors/1 HTTP/1.1


###
# POST
POST http://localhost:3000/doctors/ HTTP/1.1
Content-Type: application/json 

{
    "firstName": "Is",
    "lastName": "Doe",
    "speciality" : "cardiologist"
}


### 
# PUT
PUT http://localhost:3000/doctors/1

{
    "firstName": "Is",
    "lastName": "Doe",
    "speciality" : "cardiologist"
}
###
# DELEE

DELETE http://localhost:3000/doctors/1

###
# GET filtrée
GET http://localhost:3000/doctors?speciality=carlogue HTTP/1.1

###
# @name admin_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
# DELETE avec token
DELETE http://localhost:3000/doctors/2 HTTP/1.1
Authorization: {{admin_login.response.body.token}} 