###
#
POST http://localhost:3000/users
Content-Type: application/json

{
    "id" : 3,
    "username" : "admin",
    "password" : "admin",
    "role" : "admin",
    "email" : "mrn@mrn.mrn",
    "lastName" : "Mrn",
    "firstName" : "Mrn"

}